---

- name: update APT packages
  apt:
    update_cache: yes
    force_apt_get: yes
    upgrade: "dist"

- name: Install wget, curl, unzip
  apt:
    name: ["wget", "curl", "unzip"]
    state: present

- name: Install python3, python3-venv, python3-dev
  apt:
    name: ["python3", "python3-venv", "python3-dev"]
    state: present

- name: Install nginx
  apt:
    name: ["nginx"]
    state: present
